import numpy as np

SOURCE_RADIUS = 93.7
DETECTOR_RADIUS = 53.4

DETECTOR_ROWS = 1548
DETECTOR_COLS = 274

DETECTOR_WIDTH = 30.0 / 1524 * DETECTOR_COLS  # cm
DETECTOR_HEIGHT = 30.0  # cm

# auxiliaries
DETECTOR_PIXEL_WIDTH = DETECTOR_WIDTH / DETECTOR_COLS
DETECTOR_PIXEL_HEIGHT = DETECTOR_HEIGHT / DETECTOR_ROWS
DETECTOR_SIZE = np.array([DETECTOR_WIDTH, DETECTOR_HEIGHT])
DETECTOR_SHAPE = np.array([DETECTOR_ROWS, DETECTOR_COLS])
